name: "iOS Bump Version"
description: "update Xcode Project version and build number"
inputs:
  version:
    description: "new version string"
    required: true
  build-number:
    description: "new build number. if not set, automatically increment"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "arrow-up"
  color: "black"